version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ebc_intel
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    command: >
      bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    volumes:
      - ./backend/app:/usr/src/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ebc_intel
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PERIGON_API_KEY=${PERIGON_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    command: >
      bash -c "celery -A app.celery_app.celery worker --loglevel=info"
    volumes:
      - ./backend/app:/usr/src/app/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ebc_intel
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - PERIGON_API_KEY=${PERIGON_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
    depends_on:
      - db
      - redis

  frontend:
    build: ./frontend
    command: >
      bash -c "npm install && npm run dev -- --hostname 0.0.0.0 --port 3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  db-data:
